---
title: "multiple ENU mutation burden analysis"
output: html_document
date: "2023-10-09"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparation

## Load libraries
```{r}
library(ggplot2)
library(ggpubr)
library(rstatix)
library(ggbreak)
library(patchwork)
library(tidyr)
```

## Functions
```{r}
theme_Publication <- function(base_size=16, base_family="helvetica") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family = "")
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               #legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}
```

## Load data
```{r}
setwd("/Users/ronaldcutler/Dropbox (EinsteinMed)/Vijg-lab/Projects/mutation accumulation/231009 multiple ENU analysis/12-scWGS-SMM")

df <- read.csv("scWGS_reference.csv")

# make long
df_snv_per_mb <- gather(df, "assay", "SNVs.per.MB", scWGS.SNVs.per.MB:SMM.SNVs.per.MB, factor_key=TRUE)

df_snv_per_cell <- gather(df, "assay", "SNVs.per.cell", scWGS.SNVs.per.cell:SMM.SNVs.per.cell, factor_key=TRUE)
```

# Correlation analysis
```{r}
setwd("/Users/ronaldcutler/Dropbox (EinsteinMed)/Vijg-lab/Projects/mutation accumulation/231009 multiple ENU analysis/12-scWGS-SMM")

# SNVs per MB
pdf("SNV_per_MB_correlation.pdf",
    width = 5,
    height = 5)
ggplot() +
    geom_smooth(data = df, mapping = aes(x = scWGS.SNVs.per.MB, y = SMM.SNVs.per.MB), method="lm") +
    geom_point(df, mapping = aes(x = scWGS.SNVs.per.MB, y = SMM.SNVs.per.MB, colour = condition, shape = factor(cycle)), size = 5, alpha = 0.5) +
    stat_cor(data = df, mapping = aes(x = scWGS.SNVs.per.MB, y = SMM.SNVs.per.MB), method = "pearson", na.rm = TRUE, size = 5) +
    guides(shape=guide_legend(title=" cycle")) +
    labs(x = "scWGS", y = "SMM", title = "SNVs per MB") +
    scale_colour_Publication() +
    theme_Publication(base_size = 10)
dev.off()

pdf("SNV_per_MB_correlation_log.pdf",
    width = 5,
    height = 5)
ggplot() +
    geom_smooth(data = df, mapping = aes(x = scWGS.SNVs.per.MB, y = SMM.SNVs.per.MB), method="lm") +
    geom_point(df, mapping = aes(x = scWGS.SNVs.per.MB, y = SMM.SNVs.per.MB, colour = condition, shape = factor(cycle)), size = 5, alpha = 0.5) +
    stat_cor(data = df, mapping = aes(x = scWGS.SNVs.per.MB, y = SMM.SNVs.per.MB), method = "pearson", na.rm = TRUE, size = 5) +
      guides(shape=guide_legend(title=" cycle")) +
    labs(x = "scWGS", y = "SMM", title = "SNVs per MB") +
    scale_colour_Publication() +
    theme_Publication(base_size = 10) +
    scale_y_log10() +
    scale_x_log10()
dev.off()

# SNVs per cell
pdf("SNV_per_cell_correlation.pdf",
    width = 5,
    height = 5)
ggplot() +
    geom_smooth(data = df, mapping = aes(x = scWGS.SNVs.per.cell, y = SMM.SNVs.per.cell), method="lm") +
    geom_point(df, mapping = aes(x = scWGS.SNVs.per.cell, y = SMM.SNVs.per.cell, colour = condition, shape = factor(cycle)), size = 5, alpha = 0.5) +
    stat_cor(data = df, mapping = aes(x = scWGS.SNVs.per.cell, y = SMM.SNVs.per.cell), method = "pearson", na.rm = TRUE, size = 5) +
      guides(shape=guide_legend(title=" cycle")) +
    labs(x = "scWGS", y = "SMM", title = "SNVs per cell") +
    scale_colour_Publication() +
    theme_Publication(base_size = 10)
dev.off()

pdf("SNV_per_cell_correlation_log.pdf",
    width = 5,
    height = 5)
ggplot() +
    geom_smooth(data = df, mapping = aes(x = scWGS.SNVs.per.cell, y = SMM.SNVs.per.cell), method="lm") +
    geom_point(df, mapping = aes(x = scWGS.SNVs.per.cell, y = SMM.SNVs.per.cell, colour = condition, shape = factor(cycle)), size = 5, alpha = 0.5) +
    stat_cor(data = df, mapping = aes(x = scWGS.SNVs.per.cell, y = SMM.SNVs.per.cell), method = "pearson", na.rm = TRUE, size = 5) +
      guides(shape=guide_legend(title=" cycle")) +
    labs(x = "scWGS", y = "SMM", title = "SNVs per cell") +
    scale_colour_Publication() +
    theme_Publication(base_size = 10) +
    scale_y_log10() +
    scale_x_log10()
dev.off()
```

# Bar plots
```{r}
stats_summary <- df_snv_per_mb %>%
  group_by(condition, assay, cycle) %>%
  summarise(mean_log2fc = mean(SNVs.per.MB, na.rm = TRUE),
            sd_log2fc = sd(SNVs.per.MB, na.rm = TRUE))

pdf("SNV_per_MB_barplot.pdf",
    width = 5,
    height = 5)
ggplot(df_snv_per_mb, aes(x = factor(cycle), y = SNVs.per.MB, fill = assay)) +
    geom_bar(stat = "summary", fun.y = "mean", position = "dodge") +  # Average bar plot
      geom_errorbar(data = stats_summary, aes(x = factor(cycle), y = mean_log2fc, ymin = mean_log2fc - sd_log2fc, ymax = mean_log2fc + sd_log2fc),
                    width = 0.5, position = position_dodge(0.9)) +
    geom_point(aes(x = factor(cycle), y = SNVs.per.MB), position = position_jitterdodge(jitter.width = 0.2), size = 2, alpha = 0.5) +
    stat_compare_means(aes(group = assay), method = "t.test", label.x.npc = "center", size = 5, label = "p.signif", na.rm = TRUE, hide.ns = TRUE, vjust = 0.5) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    labs(x = "Cycle", y = "SNVs per MB") +
    scale_fill_manual(name = "assay", labels = c("scWGS", "SMM"), values = c("#7fc97f","#ef3b2c")) +
    theme_Publication() +
    facet_grid(~condition, scales = "fixed") +
    scale_y_continuous(trans=scales::pseudo_log_trans(base = 10),
                       breaks = c(0, 0.3, 1, 3, 10)) +
    theme(strip.text = element_text(size = 16),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank())
dev.off()

pdf("SNV_per_MB_barplot_free.pdf",
    width = 5,
    height = 5)
ggplot(df_snv_per_mb, aes(x = factor(cycle), y = SNVs.per.MB, fill = assay)) +
    geom_bar(stat = "summary", fun.y = "mean", position = "dodge") +  # Average bar plot
      geom_errorbar(data = stats_summary, aes(x = factor(cycle), y = mean_log2fc, ymin = mean_log2fc - sd_log2fc, ymax = mean_log2fc + sd_log2fc),
                    width = 0.5, position = position_dodge(0.9)) +
    geom_point(aes(x = factor(cycle), y = SNVs.per.MB), position = position_jitterdodge(jitter.width = 0.2), size = 2, alpha = 0.5) +
    stat_compare_means(aes(group = assay), method = "t.test", label.x.npc = "center", size = 8, label = "p.signif", na.rm = TRUE, hide.ns = TRUE, vjust = 0.5) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    labs(x = "Cycle", y = "SNVs per MB") +
    scale_fill_manual(name = "assay", labels = c("scWGS", "SMM"), values = c("#7fc97f","#ef3b2c")) +
    theme_Publication() +
    facet_wrap(~condition, scales = "free") +
    theme(strip.text = element_text(size = 16),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank())
dev.off()

stats_summary <- df_snv_per_cell %>%
  group_by(condition, assay, cycle) %>%
  summarise(mean_log2fc = mean(SNVs.per.cell, na.rm = TRUE),
            sd_log2fc = sd(SNVs.per.cell, na.rm = TRUE))

pdf("SNV_per_cell_barplot.pdf",
    width = 5,
    height = 5)
ggplot(df_snv_per_cell, aes(x = factor(cycle), y = SNVs.per.cell, fill = assay)) +
    geom_bar(stat = "summary", fun.y = "mean", position = "dodge") +  # Average bar plot
      geom_errorbar(data = stats_summary, aes(x = factor(cycle), y = mean_log2fc, ymin = mean_log2fc - sd_log2fc, ymax = mean_log2fc + sd_log2fc),
                    width = 0.5, position = position_dodge(0.9)) +
    geom_point(aes(x = factor(cycle), y = SNVs.per.cell), position = position_jitterdodge(jitter.width = 0.2), size = 2, alpha = 0.5) +
    stat_compare_means(aes(group = assay), method = "t.test", label.x.npc = "center", size = 5, label = "p.signif", na.rm = TRUE, hide.ns = TRUE, vjust = 0.5) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    labs(x = "Cycle", y = "SNVs per Cell") +
    scale_fill_manual(name = "assay", labels = c("scWGS", "SMM"), values = c("#7fc97f","#ef3b2c")) +
    theme_Publication() +
    facet_grid(~condition) +
    scale_y_log10() +
    theme(strip.text = element_text(size = 16), 
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank())
dev.off()

pdf("SNV_per_cell_barplot_free.pdf",
    width = 5,
    height = 5)
ggplot(df_snv_per_cell, aes(x = factor(cycle), y = SNVs.per.cell, fill = assay)) +
    geom_bar(stat = "summary", fun.y = "mean", position = "dodge") +  # Average bar plot
      geom_errorbar(data = stats_summary, aes(x = factor(cycle), y = mean_log2fc, ymin = mean_log2fc - sd_log2fc, ymax = mean_log2fc + sd_log2fc),
                    width = 0.5, position = position_dodge(0.9)) +
    geom_point(aes(x = factor(cycle), y = SNVs.per.cell), position = position_jitterdodge(jitter.width = 0.2), size = 2, alpha = 0.5) +
    stat_compare_means(aes(group = assay), method = "t.test", label.x.npc = "center", size = 8, label = "p.signif", na.rm = TRUE, hide.ns = TRUE, vjust = 0.5) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    labs(x = "Cycle", y = "SNVs per Cell") +
    scale_fill_manual(name = "assay", labels = c("scWGS", "SMM"), values = c("#7fc97f","#ef3b2c")) +
    theme_Publication() +
    facet_wrap(~condition, scales = "free") +
    theme(strip.text = element_text(size = 16), 
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank())
dev.off()

pdf("SNV_per_cell_boxplot.pdf",
    width = 5,
    height = 5)
ggplot(df_snv_per_cell, aes(x = factor(cycle), y = SNVs.per.cell, fill = assay)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(aes(x = factor(cycle), y = SNVs.per.cell), position = position_jitterdodge(jitter.width = 0.2), size = 2, alpha = 0.5) +
    stat_compare_means(aes(group = assay), method = "t.test", label.x.npc = "center", size = 5, label = "p.signif", na.rm = TRUE, hide.ns = TRUE, vjust = 0.5) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    labs(x = "Cycle", y = "SNVs per Cell") +
    scale_fill_manual(name = "assay", labels = c("scWGS", "SMM"), values = c("#7fc97f","#ef3b2c")) +
    theme_Publication() +
    facet_grid(~condition) +
    scale_y_log10() +
    theme(strip.text = element_text(size = 16), 
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank())
dev.off()
```